# Generated by Django 5.2.11 on 2026-04-01 11:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('sales', '0002_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-spent_at']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='spent_at',
            field=models.DateTimeField(db_column='spent_at', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.financialaccount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=10)),
                ('source_type', models.CharField(choices=[('PAYMENT', 'Paiement client'), ('EXPENSE', 'Dépense'), ('MANUAL', 'Manuel'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('account_id_value', models.BigIntegerField(db_column='account_id')),
                ('account_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('transaction_date', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_id_value', models.BigIntegerField(blank=True, db_column='expense_id', null=True)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_financial_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
