# Generated by Django 5.2.11 on 2026-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_remove_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='counter_account_id_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='counter_account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='transfer_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='source_type',
            field=models.CharField(choices=[('PAYMENT', 'Paiement client'), ('EXPENSE', 'Dépense'), ('MANUAL', 'Manuel'), ('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('TRANSFER', 'Transfert'), ('OTHER', 'Autre')], default='OTHER', max_length=20),
        ),
    ]
