# Generated by Django 5.2.11 on 2026-04-14 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_financialtransaction_counter_account_id_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discrepancy_type', models.CharField(choices=[('INVOICE_PAYMENT_MISMATCH', 'Discordance paiement facture'), ('STOCK_BALANCE_MISMATCH', 'Discordance balance stock'), ('EXPENSE_AMOUNT_MISMATCH', 'Discordance montant dépense'), ('MISSING_REFERENCE', 'Référence manquante'), ('SOFT_LINK_BROKEN', 'Lien mou cassé')], db_column='discrepancy_type', max_length=50)),
                ('object_app', models.CharField(max_length=50)),
                ('object_model', models.CharField(max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('detail', models.JSONField()),
                ('expected_value', models.TextField(blank=True, null=True)),
                ('actual_value', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DETECTED', 'Détecté'), ('AUTO_FIXED', 'Auto-corrigé'), ('MANUAL_REVIEW', 'Révision manuelle'), ('RESOLVED', 'Résolu'), ('IGNORED', 'Ignoré')], default='DETECTED', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconciliation_logs',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['discrepancy_type', '-detected_at'], name='reconciliat_discrep_e587f6_idx'), models.Index(fields=['status', '-detected_at'], name='reconciliat_status_8a74cc_idx'), models.Index(fields=['object_app', 'object_model', 'object_id'], name='reconciliat_object__a8d1aa_idx')],
            },
        ),
    ]
