# Generated by Django 5.2.11 on 2026-04-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_version_number_reconciliationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='source_type',
            field=models.CharField(choices=[('PAYMENT', 'Paiement client'), ('EXPENSE', 'Dépense'), ('SUPPLIER_PAYMENT', 'Paiement fournisseur'), ('MANUAL', 'Manuel'), ('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('TRANSFER', 'Transfert'), ('OTHER', 'Autre')], default='OTHER', max_length=30),
        ),
    ]
