# Generated by Django 5.2.11 on 2026-04-14 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Supprimer la table existante si elle existe avec une mauvaise structure
        migrations.RunSQL(
            "DROP TABLE IF EXISTS audit_logs",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name="ID de l'objet")),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion')], max_length=20, verbose_name='Action')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Valeurs anciennes')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Valeurs nouvelles')),
                ('reason', models.TextField(blank=True, verbose_name='Raison du changement')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navigateur')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'objet")),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'audit_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['changed_by', '-changed_at'], name='audit_logs_changed_72c686_idx'), models.Index(fields=['action', '-changed_at'], name='audit_logs_action_af67a2_idx')],
            },
        ),
    ]
