# Generated by Django 5.2.11 on 2026-03-23 12:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'depots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('unit_type', models.CharField(choices=[('PACK', 'Pack')], default='PACK', max_length=10)),
                ('sachets_per_pack', models.PositiveIntegerField()),
                ('default_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('TRANSFER', 'Transfert'), ('ADJUST', 'Ajustement'), ('LOSS', 'Perte')], max_length=20)),
                ('ref_type', models.CharField(choices=[('PRODUCTION_LOT', 'Lot de production'), ('INVOICE', 'Facture'), ('MANUAL', 'Manuel')], default='MANUAL', max_length=20)),
                ('ref_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('depot_from', models.ForeignKey(blank=True, db_column='depot_from_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='inventory.depot')),
                ('depot_to', models.ForeignKey(blank=True, db_column='depot_to_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='inventory.depot')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_packs', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.ForeignKey(db_column='movement_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockmovement')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_items', to='inventory.product')),
            ],
            options={
                'db_table': 'stock_movement_items',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_packs', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(db_column='depot_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.depot')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.product')),
            ],
            options={
                'db_table': 'stock_balances',
                'ordering': ['depot__name', 'product__name'],
                'unique_together': {('depot', 'product')},
            },
        ),
    ]
