# Generated by Django 5.2.11 on 2026-04-04 02:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('product_id_value', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('depot_id_value', models.BigIntegerField()),
                ('depot_name', models.CharField(max_length=255)),
                ('planned_qty_packs', models.PositiveIntegerField(default=0)),
                ('actual_qty_packs', models.PositiveIntegerField(default=0)),
                ('loss_qty_packs', models.PositiveIntegerField(default=0)),
                ('net_qty_packs', models.PositiveIntegerField(default=0)),
                ('cost_mode', models.CharField(choices=[('MANUAL', 'Manuel'), ('SEMI', 'Semi-automatique')], default='MANUAL', max_length=10)),
                ('manual_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_production_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unit_production_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('production_date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('stock_movement_id_value', models.BigIntegerField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_created', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, db_column='validated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_orders',
                'ordering': ['-production_date', '-id'],
            },
        ),
    ]
