# Generated by Django 5.2.11 on 2026-04-09 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_purchase_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('item_type', models.CharField(choices=[('RAW', 'Matière première'), ('PACKAGING', 'Emballage'), ('CONSUMABLE', 'Consommable'), ('OTHER', 'Autre')], default='RAW', max_length=20)),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('ROLL', 'Rouleau'), ('CARTON', 'Carton'), ('KG', 'Kg'), ('LITER', 'Litre')], default='PIECE', max_length=20)),
                ('current_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('last_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'supply_items',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='product_id_value',
            new_name='supply_item_id_value',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='product_name',
            new_name='supply_item_name',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='qty_packs',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='qty_units',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
    ]
