# Generated by Django 5.2.11 on 2026-04-12 23:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplyitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSupplyUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supply_item_id_value', models.BigIntegerField()),
                ('supply_item_name', models.CharField(max_length=255)),
                ('qty_units', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(db_column='production_id', on_delete=django.db.models.deletion.CASCADE, related_name='supply_usages', to='inventory.productionorder')),
            ],
            options={
                'db_table': 'production_supply_usages',
                'ordering': ['id'],
            },
        ),
    ]
