# Generated by Django 5.2.11 on 2026-04-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productionsupplyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbalance',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
