# Generated by Django 5.2.11 on 2026-04-15 02:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockbalance_version_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payable_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payable_id_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupplierPayable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('PARTIAL', 'Partiellement payée'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='OPEN', max_length=20)),
                ('payable_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payables_created', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(db_column='purchase_id', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payable', to='inventory.purchase')),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='inventory.supplier')),
            ],
            options={
                'db_table': 'supplier_payables',
                'ordering': ['-payable_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id_value', models.BigIntegerField()),
                ('account_name', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(db_column='payable_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.supplierpayable')),
            ],
            options={
                'db_table': 'supplier_payments',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
