# Generated by Django 5.2.11 on 2026-04-15 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('closure_type', models.CharField(choices=[('DAILY_CASH', 'Clôture journalière caisse'), ('MONTHLY', 'Clôture mensuelle'), ('INVENTORY', 'Clôture inventaire'), ('YEARLY', 'Clôture annuelle')], max_length=20)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('CASH', 'Trésorerie'), ('STOCK', 'Stock'), ('SALES', 'Ventes'), ('PURCHASE', 'Achats'), ('PRODUCTION', 'Production'), ('EXPENSE', 'Dépenses')], default='GLOBAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('CLOSED', 'Clôturée'), ('REOPENED', 'Rouverte')], default='CLOSED', max_length=20)),
                ('reason', models.TextField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(db_column='closed_by', on_delete=django.db.models.deletion.PROTECT, related_name='period_closures_closed', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, db_column='reopened_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='period_closures_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'period_closures',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['closure_type', 'scope', 'status'], name='period_clos_closure_15788a_idx'), models.Index(fields=['start_date', 'end_date', 'status'], name='period_clos_start_d_1a7852_idx')],
            },
        ),
    ]
