# Generated by Django 5.2.11 on 2026-03-25 13:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_stockmovement_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('client_type', models.CharField(choices=[('RETAIL', 'Détail'), ('WHOLESALE', 'Grossiste'), ('INSTITUTION', 'Institution'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('nif_rccm', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Caisse'), ('BANK', 'Banque')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'financial_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('issue_date', models.DateTimeField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('PARTIAL', 'Partiellement payée'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('sale_mode', models.CharField(choices=[('ORDER', 'Commande'), ('SELLER_OUT', 'Sortie vendeur'), ('DELIVERY', 'Livraison'), ('DIRECT', 'Vente directe')], default='DIRECT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.client')),
                ('validated_by', models.ForeignKey(blank=True, db_column='validated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_packs', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.product')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('OTHER', 'Autre')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.financialaccount')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.invoice')),
                ('received_by', models.ForeignKey(db_column='received_by', on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceStockLink',
            fields=[
                ('invoice', models.OneToOneField(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_link', serialize=False, to='sales.invoice')),
                ('stock_movement', models.OneToOneField(db_column='stock_movement_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_link', to='inventory.stockmovement')),
            ],
            options={
                'db_table': 'invoice_stock_links',
            },
        ),
    ]
