# Generated by Django 5.2.11 on 2026-03-26 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_TRANSIT', 'En cours de livraison'), ('DELIVERED', 'Livrée'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(db_column='delivered_by', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.invoice')),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-delivery_date', '-id'],
            },
        ),
    ]
