# Generated by Django 5.2.11 on 2026-04-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_tax_amount_invoice_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
